#![doc = "Peripheral access API for CW32L012 microcontrollers (generated using svd2rust v0.37.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 2;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
unsafe extern "C" {
    fn WDT();
    fn LVD();
    fn RTC();
    fn FLASHRAM();
    fn SYSCTRL();
    fn GPIOA();
    fn GPIOB();
    fn GPIOC();
    fn GPIOF();
    fn DMACH12();
    fn DMACH34();
    fn CORDIC();
    fn ADC1();
    fn ATIM();
    fn VC13();
    fn VC24();
    fn GTIM1();
    fn GTIM2();
    fn GTIM34();
    fn LPTIM();
    fn BTIM1();
    fn BTIM2();
    fn BTIM3_HALLTIM();
    fn I2C1();
    fn I2C2();
    fn SPI1();
    fn SPI23();
    fn UART1();
    fn UART2();
    fn UART3();
    fn ADC2_DAC();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[unsafe(link_section = ".vector_table.interrupts")]
#[unsafe(no_mangle)]
pub static __INTERRUPTS: [Vector; 31] = [
    Vector { _handler: WDT },
    Vector { _handler: LVD },
    Vector { _handler: RTC },
    Vector { _handler: FLASHRAM },
    Vector { _handler: SYSCTRL },
    Vector { _handler: GPIOA },
    Vector { _handler: GPIOB },
    Vector { _handler: GPIOC },
    Vector { _handler: GPIOF },
    Vector { _handler: DMACH12 },
    Vector { _handler: DMACH34 },
    Vector { _handler: CORDIC },
    Vector { _handler: ADC1 },
    Vector { _handler: ATIM },
    Vector { _handler: VC13 },
    Vector { _handler: VC24 },
    Vector { _handler: GTIM1 },
    Vector { _handler: GTIM2 },
    Vector { _handler: GTIM34 },
    Vector { _handler: LPTIM },
    Vector { _handler: BTIM1 },
    Vector { _handler: BTIM2 },
    Vector {
        _handler: BTIM3_HALLTIM,
    },
    Vector { _handler: I2C1 },
    Vector { _handler: I2C2 },
    Vector { _handler: SPI1 },
    Vector { _handler: SPI23 },
    Vector { _handler: UART1 },
    Vector { _handler: UART2 },
    Vector { _handler: UART3 },
    Vector { _handler: ADC2_DAC },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "0 - Watch Dog Timer Interrupt"]
    WDT = 0,
    #[doc = "1 - Low Voltage Detect Interrupt"]
    LVD = 1,
    #[doc = "2 - Real Time Clock Interrupt"]
    RTC = 2,
    #[doc = "3 - Flash/RAM Interrupt"]
    FLASHRAM = 3,
    #[doc = "4 - SYSCTRL Interupt"]
    SYSCTRL = 4,
    #[doc = "5 - GPIOA Interrupt"]
    GPIOA = 5,
    #[doc = "6 - GPIOB Interrupt"]
    GPIOB = 6,
    #[doc = "7 - GPIOC Interrupt"]
    GPIOC = 7,
    #[doc = "8 - GPIOF Interrupt"]
    GPIOF = 8,
    #[doc = "9 - DMA Channel 1/2 Interrupt"]
    DMACH12 = 9,
    #[doc = "10 - DMA Channel 3/4 Interrupt"]
    DMACH34 = 10,
    #[doc = "11 - desc CORDIC"]
    CORDIC = 11,
    #[doc = "12 - ADC Interrupt"]
    ADC1 = 12,
    #[doc = "13 - Advanced Timer Interrupt"]
    ATIM = 13,
    #[doc = "14 - Voltage Comparator 1/3 Interrupt"]
    VC13 = 14,
    #[doc = "15 - Voltage Comparator 2/4 Interrupt"]
    VC24 = 15,
    #[doc = "16 - General Timer1 Interrupt"]
    GTIM1 = 16,
    #[doc = "17 - General Timer1 Interrupt"]
    GTIM2 = 17,
    #[doc = "18 - General Timer3_4 Interrupt"]
    GTIM34 = 18,
    #[doc = "19 - LPTIM Interrupt"]
    LPTIM = 19,
    #[doc = "20 - Base Timer1 Interrupt"]
    BTIM1 = 20,
    #[doc = "21 - Base Timer2 Interrupt"]
    BTIM2 = 21,
    #[doc = "22 - Base Timer3 and Hall timer Interrupt"]
    BTIM3_HALLTIM = 22,
    #[doc = "23 - I2C1 Interrupt"]
    I2C1 = 23,
    #[doc = "24 - I2C2 Interrupt"]
    I2C2 = 24,
    #[doc = "25 - SPI1 Interrupt"]
    SPI1 = 25,
    #[doc = "26 - SPI23 Interrupt"]
    SPI23 = 26,
    #[doc = "27 - UART1 Interrupt"]
    UART1 = 27,
    #[doc = "28 - UART2 Interrupt"]
    UART2 = 28,
    #[doc = "29 - UART3 Interrupt"]
    UART3 = 29,
    #[doc = "30 - ADC2 and DAC Interrupt"]
    ADC2_DAC = 30,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "desc ADC1"]
pub type Adc1 = crate::Periph<adc1::RegisterBlock, 0x4000_0000>;
impl core::fmt::Debug for Adc1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Adc1").finish()
    }
}
#[doc = "desc ADC1"]
pub mod adc1;
#[doc = "ADC2"]
pub type Adc2 = crate::Periph<adc1::RegisterBlock, 0x4000_0100>;
impl core::fmt::Debug for Adc2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Adc2").finish()
    }
}
#[doc = "ADC2"]
pub use self::adc1 as adc2;
#[doc = "desc ATIM"]
pub type Atim = crate::Periph<atim::RegisterBlock, 0x4000_1400>;
impl core::fmt::Debug for Atim {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Atim").finish()
    }
}
#[doc = "desc ATIM"]
pub mod atim;
#[doc = "BGR"]
pub type Bgr = crate::Periph<bgr::RegisterBlock, 0x4000_00fc>;
impl core::fmt::Debug for Bgr {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Bgr").finish()
    }
}
#[doc = "BGR"]
pub mod bgr;
#[doc = "Base Timer 1"]
pub type Btim1 = crate::Periph<btim1::RegisterBlock, 0x4000_4800>;
impl core::fmt::Debug for Btim1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Btim1").finish()
    }
}
#[doc = "Base Timer 1"]
pub mod btim1;
#[doc = "Base Timer 2"]
pub type Btim2 = crate::Periph<btim1::RegisterBlock, 0x4000_4840>;
impl core::fmt::Debug for Btim2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Btim2").finish()
    }
}
#[doc = "Base Timer 2"]
pub use self::btim1 as btim2;
#[doc = "Base Timer 3"]
pub type Btim3 = crate::Periph<btim1::RegisterBlock, 0x4000_4880>;
impl core::fmt::Debug for Btim3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Btim3").finish()
    }
}
#[doc = "Base Timer 3"]
pub use self::btim1 as btim3;
#[doc = "desc CORDIC"]
pub type Cordic = crate::Periph<cordic::RegisterBlock, 0x4002_3400>;
impl core::fmt::Debug for Cordic {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cordic").finish()
    }
}
#[doc = "desc CORDIC"]
pub mod cordic;
#[doc = "desc CRC"]
pub type Crc = crate::Periph<crc::RegisterBlock, 0x4002_3000>;
impl core::fmt::Debug for Crc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Crc").finish()
    }
}
#[doc = "desc CRC"]
pub mod crc;
#[doc = "desc DAC"]
pub type Dac = crate::Periph<dac::RegisterBlock, 0x4000_00c0>;
impl core::fmt::Debug for Dac {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dac").finish()
    }
}
#[doc = "desc DAC"]
pub mod dac;
#[doc = "desc DMA"]
pub type Dma = crate::Periph<dma::RegisterBlock, 0x4002_0000>;
impl core::fmt::Debug for Dma {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dma").finish()
    }
}
#[doc = "desc DMA"]
pub mod dma;
#[doc = "DMA Channel 1"]
pub type Dmachannel1 = crate::Periph<dmachannel1::RegisterBlock, 0x4002_0020>;
impl core::fmt::Debug for Dmachannel1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dmachannel1").finish()
    }
}
#[doc = "DMA Channel 1"]
pub mod dmachannel1;
#[doc = "DMA Channel 2"]
pub type Dmachannel2 = crate::Periph<dmachannel1::RegisterBlock, 0x4002_0040>;
impl core::fmt::Debug for Dmachannel2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dmachannel2").finish()
    }
}
#[doc = "DMA Channel 2"]
pub use self::dmachannel1 as dmachannel2;
#[doc = "DMA Channel 3"]
pub type Dmachannel3 = crate::Periph<dmachannel1::RegisterBlock, 0x4002_0060>;
impl core::fmt::Debug for Dmachannel3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dmachannel3").finish()
    }
}
#[doc = "DMA Channel 3"]
pub use self::dmachannel1 as dmachannel3;
#[doc = "DMA Channel 4"]
pub type Dmachannel4 = crate::Periph<dmachannel1::RegisterBlock, 0x4002_0080>;
impl core::fmt::Debug for Dmachannel4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dmachannel4").finish()
    }
}
#[doc = "DMA Channel 4"]
pub use self::dmachannel1 as dmachannel4;
#[doc = "desc EAU"]
pub type Eau = crate::Periph<eau::RegisterBlock, 0x4002_3200>;
impl core::fmt::Debug for Eau {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Eau").finish()
    }
}
#[doc = "desc EAU"]
pub mod eau;
#[doc = "desc FLASH"]
pub type Flash = crate::Periph<flash::RegisterBlock, 0x4002_2000>;
impl core::fmt::Debug for Flash {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Flash").finish()
    }
}
#[doc = "desc FLASH"]
pub mod flash;
#[doc = "desc GPIOA"]
pub type Gpioa = crate::Periph<gpioa::RegisterBlock, 0x4800_0000>;
impl core::fmt::Debug for Gpioa {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpioa").finish()
    }
}
#[doc = "desc GPIOA"]
pub mod gpioa;
#[doc = "desc GPIOB"]
pub type Gpiob = crate::Periph<gpioa::RegisterBlock, 0x4800_0100>;
impl core::fmt::Debug for Gpiob {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpiob").finish()
    }
}
#[doc = "desc GPIOB"]
pub use self::gpioa as gpiob;
#[doc = "desc GPIOC"]
pub type Gpioc = crate::Periph<gpioa::RegisterBlock, 0x4800_0200>;
impl core::fmt::Debug for Gpioc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpioc").finish()
    }
}
#[doc = "desc GPIOC"]
pub use self::gpioa as gpioc;
#[doc = "desc GPIOF"]
pub type Gpiof = crate::Periph<gpioa::RegisterBlock, 0x4800_0300>;
impl core::fmt::Debug for Gpiof {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpiof").finish()
    }
}
#[doc = "desc GPIOF"]
pub use self::gpioa as gpiof;
#[doc = "General Timer 1"]
pub type Gtim1 = crate::Periph<gtim1::RegisterBlock, 0x4000_1800>;
impl core::fmt::Debug for Gtim1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gtim1").finish()
    }
}
#[doc = "General Timer 1"]
pub mod gtim1;
#[doc = "General Timer 2"]
pub type Gtim2 = crate::Periph<gtim1::RegisterBlock, 0x4000_1c00>;
impl core::fmt::Debug for Gtim2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gtim2").finish()
    }
}
#[doc = "General Timer 2"]
pub use self::gtim1 as gtim2;
#[doc = "General Timer 3"]
pub type Gtim3 = crate::Periph<gtim1::RegisterBlock, 0x4000_2400>;
impl core::fmt::Debug for Gtim3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gtim3").finish()
    }
}
#[doc = "General Timer 3"]
pub use self::gtim1 as gtim3;
#[doc = "General Timer 4"]
pub type Gtim4 = crate::Periph<gtim1::RegisterBlock, 0x4000_2800>;
impl core::fmt::Debug for Gtim4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gtim4").finish()
    }
}
#[doc = "General Timer 4"]
pub use self::gtim1 as gtim4;
#[doc = "HALL Timer"]
pub type Halltim = crate::Periph<halltim::RegisterBlock, 0x4000_6400>;
impl core::fmt::Debug for Halltim {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Halltim").finish()
    }
}
#[doc = "HALL Timer"]
pub mod halltim;
#[doc = "desc I2C1"]
pub type I2c1 = crate::Periph<i2c1::RegisterBlock, 0x4000_5800>;
impl core::fmt::Debug for I2c1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c1").finish()
    }
}
#[doc = "desc I2C1"]
pub mod i2c1;
#[doc = "desc I2C2"]
pub type I2c2 = crate::Periph<i2c1::RegisterBlock, 0x4000_5c00>;
impl core::fmt::Debug for I2c2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c2").finish()
    }
}
#[doc = "desc I2C2"]
pub use self::i2c1 as i2c2;
#[doc = "desc IRMOD"]
pub type Irmod = crate::Periph<irmod::RegisterBlock, 0x4000_4080>;
impl core::fmt::Debug for Irmod {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Irmod").finish()
    }
}
#[doc = "desc IRMOD"]
pub mod irmod;
#[doc = "desc IWDT"]
pub type Iwdt = crate::Periph<iwdt::RegisterBlock, 0x4000_5000>;
impl core::fmt::Debug for Iwdt {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Iwdt").finish()
    }
}
#[doc = "desc IWDT"]
pub mod iwdt;
#[doc = "desc LPTIM"]
pub type Lptim = crate::Periph<lptim::RegisterBlock, 0x4000_6000>;
impl core::fmt::Debug for Lptim {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lptim").finish()
    }
}
#[doc = "desc LPTIM"]
pub mod lptim;
#[doc = "desc UART1"]
pub type Uart1 = crate::Periph<uart1::RegisterBlock, 0x4000_0c00>;
impl core::fmt::Debug for Uart1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart1").finish()
    }
}
#[doc = "desc UART1"]
pub mod uart1;
#[doc = "desc UART2"]
pub type Uart2 = crate::Periph<uart1::RegisterBlock, 0x4000_1000>;
impl core::fmt::Debug for Uart2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart2").finish()
    }
}
#[doc = "desc UART2"]
pub use self::uart1 as uart2;
#[doc = "desc UART3"]
pub type Uart3 = crate::Periph<uart1::RegisterBlock, 0x4000_2000>;
impl core::fmt::Debug for Uart3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart3").finish()
    }
}
#[doc = "desc UART3"]
pub use self::uart1 as uart3;
#[doc = "desc LVD"]
pub type Lvd = crate::Periph<lvd::RegisterBlock, 0x4000_00a4>;
impl core::fmt::Debug for Lvd {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lvd").finish()
    }
}
#[doc = "desc LVD"]
pub mod lvd;
#[doc = "desc OPA1"]
pub type Opa1 = crate::Periph<opa1::RegisterBlock, 0x4000_00b0>;
impl core::fmt::Debug for Opa1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Opa1").finish()
    }
}
#[doc = "desc OPA1"]
pub mod opa1;
#[doc = "desc OPA2"]
pub type Opa2 = crate::Periph<opa1::RegisterBlock, 0x4000_00b8>;
impl core::fmt::Debug for Opa2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Opa2").finish()
    }
}
#[doc = "desc OPA2"]
pub use self::opa1 as opa2;
#[doc = "desc RAM"]
pub type Ram = crate::Periph<ram::RegisterBlock, 0x4002_2400>;
impl core::fmt::Debug for Ram {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ram").finish()
    }
}
#[doc = "desc RAM"]
pub mod ram;
#[doc = "desc RTC"]
pub type Rtc = crate::Periph<rtc::RegisterBlock, 0x4000_4400>;
impl core::fmt::Debug for Rtc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc").finish()
    }
}
#[doc = "desc RTC"]
pub mod rtc;
#[doc = "desc SPI1"]
pub type Spi1 = crate::Periph<spi1::RegisterBlock, 0x4000_0800>;
impl core::fmt::Debug for Spi1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi1").finish()
    }
}
#[doc = "desc SPI1"]
pub mod spi1;
#[doc = "desc SPI2"]
pub type Spi2 = crate::Periph<spi1::RegisterBlock, 0x4000_0400>;
impl core::fmt::Debug for Spi2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi2").finish()
    }
}
#[doc = "desc SPI2"]
pub use self::spi1 as spi2;
#[doc = "desc SPI3"]
pub type Spi3 = crate::Periph<spi1::RegisterBlock, 0x4000_3400>;
impl core::fmt::Debug for Spi3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi3").finish()
    }
}
#[doc = "desc SPI3"]
pub use self::spi1 as spi3;
#[doc = "System Ctrl"]
pub type Sysctrl = crate::Periph<sysctrl::RegisterBlock, 0x4000_4000>;
impl core::fmt::Debug for Sysctrl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sysctrl").finish()
    }
}
#[doc = "System Ctrl"]
pub mod sysctrl;
#[doc = "desc VC1"]
pub type Vc1 = crate::Periph<vc1::RegisterBlock, 0x4000_0084>;
impl core::fmt::Debug for Vc1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Vc1").finish()
    }
}
#[doc = "desc VC1"]
pub mod vc1;
#[doc = "desc VC12REF"]
pub type Vc12ref = crate::Periph<vc12ref::RegisterBlock, 0x4000_0080>;
impl core::fmt::Debug for Vc12ref {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Vc12ref").finish()
    }
}
#[doc = "desc VC12REF"]
pub mod vc12ref;
#[doc = "desc VC2"]
pub type Vc2 = crate::Periph<vc1::RegisterBlock, 0x4000_0094>;
impl core::fmt::Debug for Vc2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Vc2").finish()
    }
}
#[doc = "desc VC2"]
pub use self::vc1 as vc2;
#[doc = "desc VC3"]
pub type Vc3 = crate::Periph<vc1::RegisterBlock, 0x4000_0184>;
impl core::fmt::Debug for Vc3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Vc3").finish()
    }
}
#[doc = "desc VC3"]
pub use self::vc1 as vc3;
#[doc = "desc VC34REF"]
pub type Vc34ref = crate::Periph<vc12ref::RegisterBlock, 0x4000_0180>;
impl core::fmt::Debug for Vc34ref {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Vc34ref").finish()
    }
}
#[doc = "desc VC34REF"]
pub use self::vc12ref as vc34ref;
#[doc = "desc VC4"]
pub type Vc4 = crate::Periph<vc1::RegisterBlock, 0x4000_0194>;
impl core::fmt::Debug for Vc4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Vc4").finish()
    }
}
#[doc = "desc VC4"]
pub use self::vc1 as vc4;
#[doc = "desc WWDT"]
pub type Wwdt = crate::Periph<wwdt::RegisterBlock, 0x4000_5400>;
impl core::fmt::Debug for Wwdt {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wwdt").finish()
    }
}
#[doc = "desc WWDT"]
pub mod wwdt;
#[unsafe(no_mangle)]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "ADC1"]
    pub adc1: Adc1,
    #[doc = "ADC2"]
    pub adc2: Adc2,
    #[doc = "ATIM"]
    pub atim: Atim,
    #[doc = "BGR"]
    pub bgr: Bgr,
    #[doc = "BTIM1"]
    pub btim1: Btim1,
    #[doc = "BTIM2"]
    pub btim2: Btim2,
    #[doc = "BTIM3"]
    pub btim3: Btim3,
    #[doc = "CORDIC"]
    pub cordic: Cordic,
    #[doc = "CRC"]
    pub crc: Crc,
    #[doc = "DAC"]
    pub dac: Dac,
    #[doc = "DMA"]
    pub dma: Dma,
    #[doc = "DMACHANNEL1"]
    pub dmachannel1: Dmachannel1,
    #[doc = "DMACHANNEL2"]
    pub dmachannel2: Dmachannel2,
    #[doc = "DMACHANNEL3"]
    pub dmachannel3: Dmachannel3,
    #[doc = "DMACHANNEL4"]
    pub dmachannel4: Dmachannel4,
    #[doc = "EAU"]
    pub eau: Eau,
    #[doc = "FLASH"]
    pub flash: Flash,
    #[doc = "GPIOA"]
    pub gpioa: Gpioa,
    #[doc = "GPIOB"]
    pub gpiob: Gpiob,
    #[doc = "GPIOC"]
    pub gpioc: Gpioc,
    #[doc = "GPIOF"]
    pub gpiof: Gpiof,
    #[doc = "GTIM1"]
    pub gtim1: Gtim1,
    #[doc = "GTIM2"]
    pub gtim2: Gtim2,
    #[doc = "GTIM3"]
    pub gtim3: Gtim3,
    #[doc = "GTIM4"]
    pub gtim4: Gtim4,
    #[doc = "HALLTIM"]
    pub halltim: Halltim,
    #[doc = "I2C1"]
    pub i2c1: I2c1,
    #[doc = "I2C2"]
    pub i2c2: I2c2,
    #[doc = "IRMOD"]
    pub irmod: Irmod,
    #[doc = "IWDT"]
    pub iwdt: Iwdt,
    #[doc = "LPTIM"]
    pub lptim: Lptim,
    #[doc = "UART1"]
    pub uart1: Uart1,
    #[doc = "UART2"]
    pub uart2: Uart2,
    #[doc = "UART3"]
    pub uart3: Uart3,
    #[doc = "LVD"]
    pub lvd: Lvd,
    #[doc = "OPA1"]
    pub opa1: Opa1,
    #[doc = "OPA2"]
    pub opa2: Opa2,
    #[doc = "RAM"]
    pub ram: Ram,
    #[doc = "RTC"]
    pub rtc: Rtc,
    #[doc = "SPI1"]
    pub spi1: Spi1,
    #[doc = "SPI2"]
    pub spi2: Spi2,
    #[doc = "SPI3"]
    pub spi3: Spi3,
    #[doc = "SYSCTRL"]
    pub sysctrl: Sysctrl,
    #[doc = "VC1"]
    pub vc1: Vc1,
    #[doc = "VC12REF"]
    pub vc12ref: Vc12ref,
    #[doc = "VC2"]
    pub vc2: Vc2,
    #[doc = "VC3"]
    pub vc3: Vc3,
    #[doc = "VC34REF"]
    pub vc34ref: Vc34ref,
    #[doc = "VC4"]
    pub vc4: Vc4,
    #[doc = "WWDT"]
    pub wwdt: Wwdt,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        unsafe { DEVICE_PERIPHERALS = true }
        Peripherals {
            adc1: unsafe { Adc1::steal() },
            adc2: unsafe { Adc2::steal() },
            atim: unsafe { Atim::steal() },
            bgr: unsafe { Bgr::steal() },
            btim1: unsafe { Btim1::steal() },
            btim2: unsafe { Btim2::steal() },
            btim3: unsafe { Btim3::steal() },
            cordic: unsafe { Cordic::steal() },
            crc: unsafe { Crc::steal() },
            dac: unsafe { Dac::steal() },
            dma: unsafe { Dma::steal() },
            dmachannel1: unsafe { Dmachannel1::steal() },
            dmachannel2: unsafe { Dmachannel2::steal() },
            dmachannel3: unsafe { Dmachannel3::steal() },
            dmachannel4: unsafe { Dmachannel4::steal() },
            eau: unsafe { Eau::steal() },
            flash: unsafe { Flash::steal() },
            gpioa: unsafe { Gpioa::steal() },
            gpiob: unsafe { Gpiob::steal() },
            gpioc: unsafe { Gpioc::steal() },
            gpiof: unsafe { Gpiof::steal() },
            gtim1: unsafe { Gtim1::steal() },
            gtim2: unsafe { Gtim2::steal() },
            gtim3: unsafe { Gtim3::steal() },
            gtim4: unsafe { Gtim4::steal() },
            halltim: unsafe { Halltim::steal() },
            i2c1: unsafe { I2c1::steal() },
            i2c2: unsafe { I2c2::steal() },
            irmod: unsafe { Irmod::steal() },
            iwdt: unsafe { Iwdt::steal() },
            lptim: unsafe { Lptim::steal() },
            uart1: unsafe { Uart1::steal() },
            uart2: unsafe { Uart2::steal() },
            uart3: unsafe { Uart3::steal() },
            lvd: unsafe { Lvd::steal() },
            opa1: unsafe { Opa1::steal() },
            opa2: unsafe { Opa2::steal() },
            ram: unsafe { Ram::steal() },
            rtc: unsafe { Rtc::steal() },
            spi1: unsafe { Spi1::steal() },
            spi2: unsafe { Spi2::steal() },
            spi3: unsafe { Spi3::steal() },
            sysctrl: unsafe { Sysctrl::steal() },
            vc1: unsafe { Vc1::steal() },
            vc12ref: unsafe { Vc12ref::steal() },
            vc2: unsafe { Vc2::steal() },
            vc3: unsafe { Vc3::steal() },
            vc34ref: unsafe { Vc34ref::steal() },
            vc4: unsafe { Vc4::steal() },
            wwdt: unsafe { Wwdt::steal() },
        }
    }
}
